org: stefan12
app: aws
service: aws

custom:
  secrets: ${file(secrets.json)}

provider: 
  name: aws 
  runtime: nodejs12.x 
  stage: production
  region: us-east-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV} 

functions: 
  app: 
    handler: app.server
    events: 
      - http:
          path: / 
          method: ANY 
          cors: true 
      - http:
          path: /{proxy+} 
          method: ANY 
          cors: true
